### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ghost** [Airsaid/ChordView#1]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards.

**Comment by Airsaid** [comment]
I am very happy that you can design icons for my project! We can discuss it together here.

**Comment by ghost** [comment]
I will prepare and present a few samples for you.

**Comment by ghost** [comment]
![chordv ew](https://user-images.githubusercontent.com/36993664/43049002-51b2ac92-8df9-11e8-97df-f563a2390349.jpg)

- The first logo references a preview of the program.
- The second logo is the combination of the guitar handle and the letter c.

**Comment by ghost** [comment]
![untitled-2](https://user-images.githubusercontent.com/36993664/43050595-51709d5a-8e14-11e8-9300-3d2eac882b98.jpg)

**Comment by Airsaid** [comment]
Thank you very much! I like both, but if I have to choose one, I will choose the first one. Because it is closer to the project, others can better understand what the project does.

**Comment by ghost** [comment]
I'm glad you like it. You are right, the first logo represents the project more. Hopefully it benefits your business. I sent you a PR. Good work, if you have another design job, you can write.

https://github.com/Airsaid/ChordView/pull/2

Best Regards.

**Comment by Airsaid** [comment]
Thank you again for your contribution to the project.
